
#Enable simple harvesting and replanting with right click
"Simple Harvest" = true
#Curiosity Mode: sneak + right click with on block to get info in chat
Curiosity = false
#List of crops to process with their ages
"Crops List" = [
    "Block{minecraft:potatoes}[age=7]",
    "Block{minecraft:carrots}[age=7]",
    "Block{minecraft:wheat}[age=7]",
    "Block{minecraft:beetroots}[age=3]",
    "Block{minecraft:nether_wart}[age=3]",
    "Block{pamhc2crops:pamagavecrop}[age=7]",
    "Block{pamhc2crops:pamamaranthcrop}[age=7]",
    "Block{pamhc2crops:pamarrowrootcrop}[age=7]",
    "Block{pamhc2crops:pamartichokecrop}[age=7]",
    "Block{pamhc2crops:pamasparaguscrop}[age=7]",
    "Block{pamhc2crops:pambarleycrop}[age=7]",
    "Block{pamhc2crops:pambeancrop}[age=7]",
    "Block{pamhc2crops:pambellpeppercrop}[age=7]",
    "Block{pamhc2crops:pamblackberrycrop}[age=7]",
    "Block{pamhc2crops:pamblueberrycrop}[age=7]",
    "Block{pamhc2crops:pambroccolicrop}[age=7]",
    "Block{pamhc2crops:pambrusselsproutcrop}[age=7]",
    "Block{pamhc2crops:pamcabbagecactusfruitcrop}[age=7]",
    "Block{pamhc2crops:pamcandleberrycrop}[age=7]",
    "Block{pamhc2crops:pamcantaloupecrop}[age=7]",
    "Block{pamhc2crops:pamcassavacrop}[age=7]",
    "Block{pamhc2crops:pamcauliflowercrop}[age=7]",
    "Block{pamhc2crops:pamcelerycrop}[age=7]",
    "Block{pamhc2crops:pamchickpeacrop}[age=7]",
    "Block{pamhc2crops:pamchilipeppercrop}[age=7]",
    "Block{pamhc2crops:pamcoffeebeancrop}[age=7]",
    "Block{pamhc2crops:pamcorncrop}[age=7]",
    "Block{pamhc2crops:pamcottoncrop}[age=7]",
    "Block{pamhc2crops:pamcranberrycrop}[age=7]",
    "Block{pamhc2crops:pamcucumbercrop}[age=7]",
    "Block{pamhc2crops:pameggplantcrop}[age=7]",
    "Block{pamhc2crops:pamelderberrycrop}[age=7]",
    "Block{pamhc2crops:pamflaxcrop}[age=7]",
    "Block{pamhc2crops:pamgarliccrop}[age=7]",
    "Block{pamhc2crops:pamgrapecrop}[age=7]",
    "Block{pamhc2crops:pamgreengrapecrop}[age=7]",
    "Block{pamhc2crops:pamgingercrop}[age=7]",
    "Block{pamhc2crops:pamhuckleberrycrop}[age=7]",
    "Block{pamhc2crops:pamjicamacrop}[age=7]",
    "Block{pamhc2crops:pamjuniperberrycrop}[age=7]",
    "Block{pamhc2crops:pamjutecrop}[age=7]",
    "Block{pamhc2crops:pamkalecrop}[age=7]",
    "Block{pamhc2crops:pamkenafcrop}[age=7]",
    "Block{pamhc2crops:pamkiwicrop}[age=7]",
    "Block{pamhc2crops:pamkohlrabicrop}[age=7]",
    "Block{pamhc2crops:pamleekcrop}[age=7]",
    "Block{pamhc2crops:pamlentilcrop}[age=7]",
    "Block{pamhc2crops:pamlettucecrop}[age=7]",
    "Block{pamhc2crops:pammillecrop}[age=7]",
    "Block{pamhc2crops:pammulberrycrop}[age=7]",
    "Block{pamhc2crops:pammustardseedscrop}[age=7]",
    "Block{pamhc2crops:pamoatscrop}[age=7]",
    "Block{pamhc2crops:pamokracrop}[age=7]",
    "Block{pamhc2crops:pamonioncrop}[age=7]",
    "Block{pamhc2crops:pamparsnipcrop}[age=7]",
    "Block{pamhc2crops:pampeanutcrop}[age=7]",
    "Block{pamhc2crops:pampeascrop}[age=7]",
    "Block{pamhc2crops:pampineapplecrop}[age=7]",
    "Block{pamhc2crops:pamquinoacrop}[age=7]",
    "Block{pamhc2crops:pamradishcrop}[age=7]",
    "Block{pamhc2crops:pamraspberrycrop}[age=7]",
    "Block{pamhc2crops:pamrhubarbcrop}[age=7]",
    "Block{pamhc2crops:pamricecrop}[age=7]",
    "Block{pamhc2crops:pamrutabagacrop}[age=7]",
    "Block{pamhc2crops:pamryecrop}[age=7]",
    "Block{pamhc2crops:pamscallioncrop}[age=7]",
    "Block{pamhc2crops:pamsesameseedcrop}[age=7]",
    "Block{pamhc2crops:pamsisalcrop}[age=7]",
    "Block{pamhc2crops:pamsoybeancrop}[age=7]",
    "Block{pamhc2crops:pamspiceleafcrop}[age=7]",
    "Block{pamhc2crops:pamspinachcrop}[age=7]",
    "Block{pamhc2crops:pamstrawberrycrop}[age=7]",
    "Block{pamhc2crops:pamsweetpotatocrop}[age=7]",
    "Block{pamhc2crops:pamtarocrop}[age=7]",
    "Block{pamhc2crops:pamtealeafcrop}[age=7]",
    "Block{pamhc2crops:pamtomatillocrop}[age=7]",
    "Block{pamhc2crops:pamtomatocrop}[age=7]",
    "Block{pamhc2crops:pamturnipcrop}[age=7]",
    "Block{pamhc2crops:pamwaterchestnutcrop}[age=7]",
    "Block{pamhc2crops:pamwhitemushroomcrop}[age=7]",
    "Block{pamhc2crops:pamwintersquashcrop}[age=7]",
    "Block{pamhc2crops:pamzucchinicrop}[age=7]",
    "Block{pamhc2crops:pamcrop}[age=7]",
]
#Amount of XP given
#Range: > 1
"XP Amount" = 1
#Chance in % of XP orb spawning after harvest done
#Range: 1 ~ 100
Chance = 100
